/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.GroupLayout.Alignment;

import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import dao.AdminDAO;
import dao.CategoryDAO;
import dao.ProductDAO;
import objs.Category;
import objs.Product;
import uistyle.WJTextFieldNumber;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @author Daniel
 */
@SuppressWarnings("serial")
public class ModifyProduct extends javax.swing.JFrame {

    /**
     * Creates new form agregarProducto 
     */
	Product prInt = null;
	PanelProducts pnlProd = null;
    public ModifyProduct(Product pr) {
    	prInt = pr;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        
        txtDescription.setText(prInt.getDescription());
        txtName.setText(prInt.getName());
        txtPurchasePrice.setText(String.valueOf( prInt.getPrice()));
        txtId.setText(String.valueOf(prInt.getId()));
        txtQuantity.setText(String.valueOf(prInt.getStock()));
        txtSalePrice.setText(String.valueOf(prInt.getPrice()));
        comboBoxCategories.setSelectedItem(prInt.categoryname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({ "rawtypes", "unchecked" })
	private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelQuantity = new javax.swing.JLabel();
        txtQuantity = new WJTextFieldNumber("");
        txtQuantity.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		if(!tools.Utils.noempryString(txtQuantity.getText(), 1)) {
        			
        			txtQuantity.setText("0");
        		}
        	}
        });
        labelDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        labelPurchasePrice = new javax.swing.JLabel();
        txtPurchasePrice = new javax.swing.JTextField();
        txtPurchasePrice.setEditable(false);
        labelSalePrice = new javax.swing.JLabel();
        txtSalePrice = new WJTextFieldNumber("");
        txtSalePrice.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		if(!tools.Utils.noempryString(txtSalePrice.getText(), 1)) {
        			txtSalePrice.setText("0");
        		}
        	}
        });
        btnCancel = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labelName.setText("Nombre:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            } 
        });

        labelQuantity.setText("Cantidad:");

        labelDescription.setText("Descripción:");

        labelPurchasePrice.setText("Costo Promedio P.");

        labelSalePrice.setText("Precio de Venta:");

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        
        lblId = new JLabel();
        lblId.setText("#id");
        
        txtId = new JTextField();
        txtId.setEditable(false);
        
        labelSalePrice_1 = new JLabel();
        labelSalePrice_1.setText("Precio de Venta:");
        
        comboBoxCategories = new JComboBox();
        
        comboBoxCategories.addItem("---");
        catsT =  CategoryDAO.read();
        AdminDAO.closeConnection();
        for (int i = 0; i < catsT.size(); i++) {
        	comboBoxCategories	.addItem(catsT.get(i).getName());
		}
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(labelQuantity, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        							.addComponent(labelDescription)
        							.addComponent(labelName, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))
        						.addComponent(lblId, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        						.addComponent(labelPurchasePrice))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(txtId, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        						.addComponent(txtName, Alignment.LEADING, 264, 264, Short.MAX_VALUE)
        						.addComponent(txtQuantity, Alignment.LEADING, 264, 264, Short.MAX_VALUE)
        						.addComponent(txtDescription, Alignment.LEADING, 264, 264, Short.MAX_VALUE)
        						.addComponent(txtPurchasePrice, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(labelSalePrice, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(txtSalePrice, 264, 264, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(labelSalePrice_1, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(comboBoxCategories, 0, 264, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(btnModify)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnCancel)))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(10)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblId)
        				.addComponent(txtId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(17)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(labelName))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(labelQuantity)
        				.addComponent(txtQuantity, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtDescription, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(labelDescription))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(labelPurchasePrice)
        				.addComponent(txtPurchasePrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(labelSalePrice)
        				.addComponent(txtSalePrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(labelSalePrice_1)
        				.addComponent(comboBoxCategories, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnCancel)
        				.addComponent(btnModify))
        			.addGap(36))
        );
        jPanel1.setLayout(jPanel1Layout);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
    	if (tools.Utils.noempryString(txtName.getText(),3) && 
    			tools.Utils.noempryString(txtName.getText(),3) &&
    			comboBoxCategories.getSelectedIndex() != 0
    			) {
//    		ProductDAO.update(new Product(id, name, stk, desk, cpp, pric, cat));
    		ProductDAO.update(new Product(Integer.valueOf(txtId.getText()),
    				txtName.getText(), 
    				Double.valueOf(txtQuantity.getText()), 
    				txtDescription.getText(),
    				Double.valueOf(txtPurchasePrice.getText()), 
    				Double.valueOf(txtSalePrice.getText()),
    				catsT.get(comboBoxCategories.getSelectedIndex()-1).getId()));
    		pnlProd.getData();
    		
    		this.dispose();
    	}else {
    		JOptionPane.showMessageDialog(null, "Rebice los campos a llenar", "Alert", JOptionPane.WARNING_MESSAGE);
    	}
         
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyProduct(new Product(1, "peras", 32.2, "comida mama", 0.23, 1.2, 1)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnModify;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPurchasePrice;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelSalePrice;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPurchasePrice;
//    private javax.swing.JTextField txtQuantity;
    private WJTextFieldNumber txtQuantity;
//    private javax.swing.JTextField txtSalePrice;
    private WJTextFieldNumber txtSalePrice;
    private JLabel lblId; 
    private JTextField txtId;
    private JLabel labelSalePrice_1;
    private JComboBox<String> comboBoxCategories;
    ArrayList<Category> catsT =  null;
}
