/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
 
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class PanelClients extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    DefaultTableModel model; 
    public PanelClients() { 
        initComponents();
        
        model = new DefaultTableModel();
        model.addColumn("Cedula");
        model.addColumn("Nombre");
        model.addColumn("Telefono");
        model.addColumn("Direccion");
        this.tableClients.setModel(model);
        
        /*clienteDAO con = new clienteDAO();
        con.conectar();
        int clients = con.contarClientes();
        System.out.println("Clientes hay: "+ clients);
        */
        
        
        //select count(*) from libros
        /*
        if(prod.Consultar(idProducto, idRestaurante) == 1){
            List producto = prod.ConsultarTodo(idProducto);
            info[0] = Integer.toString(idProducto);
            info[1] = (String) (producto.get(0));
            info[2] = Integer.toString(cantidad);
            String descuento =  (String) producto.get(2);
            double porcentaje = cantidad*(Integer.valueOf((String) producto.get(1))- (Integer.valueOf((String) producto.get(1))*Double.valueOf("0."+descuento)));
            info[3] = String.valueOf(porcentaje);
            model.addRow(info);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneClients = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnAddClient = new javax.swing.JButton();
        btnModifyClient = new javax.swing.JButton();
        btnDeleteClient = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.BorderLayout());

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Celular", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneClients.setViewportView(tableClients);
        if (tableClients.getColumnModel().getColumnCount() > 0) {
            tableClients.getColumnModel().getColumn(0).setResizable(false);
            tableClients.getColumnModel().getColumn(1).setResizable(false);
            tableClients.getColumnModel().getColumn(2).setResizable(false);
            tableClients.getColumnModel().getColumn(3).setResizable(false);
        }

        add(scrollPaneClients, java.awt.BorderLayout.CENTER);

        panelButtons.setLayout(new java.awt.GridLayout(0, 1));

        btnAddClient.setText("Agregar Cliente");
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });
        panelButtons.add(btnAddClient);

        btnModifyClient.setText("Modificar Cliente");
        btnModifyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyClientActionPerformed(evt);
            }
        });
        panelButtons.add(btnModifyClient);

        btnDeleteClient.setText("Eliminar Cliente");
        btnDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClientActionPerformed(evt);
            }
        });
        panelButtons.add(btnDeleteClient);

        add(panelButtons, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyClientActionPerformed
        // TODO add your handling code here:
        new ModifyClient();
    }//GEN-LAST:event_btnModifyClientActionPerformed

    private void btnDeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClientActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnDeleteClientActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        // TODO add your handling code here:
        
        new AddClient();
    }//GEN-LAST:event_btnAddClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnDeleteClient;
    private javax.swing.JButton btnModifyClient;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JScrollPane scrollPaneClients;
    private javax.swing.JTable tableClients;
    // End of variables declaration//GEN-END:variables
    
    //////////////////////////// BACKEND//////////////////////////////////
    public void upgradaData(JTable tb) {
    	DefaultTableModel modelTb = new DefaultTableModel() {
    		   public boolean isCellEditable (int row, int column) {
    			   return false;
    		   }
    	};
    	
    	// add cols
    	modelTb.addColumn("");
    	//generate consult
    	
    	
    }
}
