/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class PanelCredits extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public PanelCredits() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneCredits = new javax.swing.JScrollPane();
        tableCredits = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnAddCredit = new javax.swing.JButton();
        btnModifyCredit = new javax.swing.JButton();
        btnDeleteCredit = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.BorderLayout());

        tableCredits.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        	},
        	new String[] {
        		"Cedula", "Nombre", "Telefono", "Deuda", "Fecha"
        	}
        ));
        scrollPaneCredits.setViewportView(tableCredits);
        if (tableCredits.getColumnModel().getColumnCount() > 0) {
            tableCredits.getColumnModel().getColumn(0).setResizable(false);
            tableCredits.getColumnModel().getColumn(1).setResizable(false);
            tableCredits.getColumnModel().getColumn(2).setResizable(false);
            tableCredits.getColumnModel().getColumn(3).setResizable(false);
            tableCredits.getColumnModel().getColumn(4).setResizable(false);
        }

        add(scrollPaneCredits, java.awt.BorderLayout.CENTER);

        panelButtons.setLayout(new java.awt.GridLayout(0, 1));

        btnAddCredit.setText("Agregar Credito");
        btnAddCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCreditActionPerformed(evt);
            }
        });
        panelButtons.add(btnAddCredit);

        btnModifyCredit.setText("Modificar Credito");
        btnModifyCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCreditActionPerformed(evt);
            }
        });
        panelButtons.add(btnModifyCredit);

        btnDeleteCredit.setText("Eliminar Credito");
        btnDeleteCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCreditActionPerformed(evt);
            }
        });
        panelButtons.add(btnDeleteCredit);

        btnPay.setText("Abonar");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        panelButtons.add(btnPay);

        add(panelButtons, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCreditActionPerformed
        // TODO add your handling code here:
        new ModifyCredit();
    }//GEN-LAST:event_btnModifyCreditActionPerformed

    private void btnDeleteCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCreditActionPerformed

    private void btnAddCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCreditActionPerformed
        // TODO add your handling code here:
        
        new AddCredit();
    }//GEN-LAST:event_btnAddCreditActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        /*
        if(hay un credito seleccionado == TRUE){
            
            PaysDetails pay = new PaysDetails();
            pay.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un credito");
        }
        */
        
        //Esto de abajo lo borras cuando hagas el condicional de arriba :v
        JOptionPane.showMessageDialog(this, "Seleccione un credito");
        PaysDetails pay = new PaysDetails();
        pay.setVisible(true);
    }//GEN-LAST:event_btnPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCredit;
    private javax.swing.JButton btnDeleteCredit;
    private javax.swing.JButton btnModifyCredit;
    private javax.swing.JButton btnPay;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JScrollPane scrollPaneCredits;
    private javax.swing.JTable tableCredits;
    // End of variables declaration//GEN-END:variables
}
