/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Daniel
 */
public class PanelReports extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public PanelReports() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDailyReport = new javax.swing.JPanel();
        labelDailyReport = new javax.swing.JLabel();
        scrollPaneDailyReport = new javax.swing.JScrollPane();
        tableDailyReport = new javax.swing.JTable();
        panelTotalAmountDaily = new javax.swing.JPanel();
        labelTotalDailyNonEditable = new javax.swing.JLabel();
        labelTotalDailyEditable = new javax.swing.JLabel();
        panelWeeklyReport = new javax.swing.JPanel();
        labelWeeklyReport = new javax.swing.JLabel();
        scrollPaneWeeklyReport = new javax.swing.JScrollPane();
        tableWeeklyReport = new javax.swing.JTable();
        panelTotalAmountWeekly = new javax.swing.JPanel();
        labelTotalWeeklyNonEditable = new javax.swing.JLabel();
        labelTotalWeeklyEditable = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.GridLayout(1, 0));

        panelDailyReport.setLayout(new javax.swing.BoxLayout(panelDailyReport, javax.swing.BoxLayout.Y_AXIS));

        labelDailyReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDailyReport.setText("Informe Diario");
        labelDailyReport.setMaximumSize(new java.awt.Dimension(343, 16));
        labelDailyReport.setMinimumSize(new java.awt.Dimension(343, 16));
        labelDailyReport.setPreferredSize(new java.awt.Dimension(343, 16));
        panelDailyReport.add(labelDailyReport);

        tableDailyReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneDailyReport.setViewportView(tableDailyReport);
        if (tableDailyReport.getColumnModel().getColumnCount() > 0) {
            tableDailyReport.getColumnModel().getColumn(0).setResizable(false);
            tableDailyReport.getColumnModel().getColumn(1).setResizable(false);
            tableDailyReport.getColumnModel().getColumn(2).setResizable(false);
        }

        panelDailyReport.add(scrollPaneDailyReport);

        panelTotalAmountDaily.setLayout(new java.awt.GridLayout(1, 0));

        labelTotalDailyNonEditable.setText("Valor total:");
        panelTotalAmountDaily.add(labelTotalDailyNonEditable);

        labelTotalDailyEditable.setText("0.0");
        labelTotalDailyEditable.setMinimumSize(new java.awt.Dimension(80, 16));
        labelTotalDailyEditable.setPreferredSize(new java.awt.Dimension(76, 16));
        panelTotalAmountDaily.add(labelTotalDailyEditable);

        panelDailyReport.add(panelTotalAmountDaily);

        add(panelDailyReport);

        panelWeeklyReport.setLayout(new javax.swing.BoxLayout(panelWeeklyReport, javax.swing.BoxLayout.Y_AXIS));

        labelWeeklyReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWeeklyReport.setText("Informe Semanal");
        labelWeeklyReport.setMaximumSize(new java.awt.Dimension(343, 16));
        labelWeeklyReport.setMinimumSize(new java.awt.Dimension(343, 16));
        labelWeeklyReport.setPreferredSize(new java.awt.Dimension(343, 16));
        panelWeeklyReport.add(labelWeeklyReport);

        tableWeeklyReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneWeeklyReport.setViewportView(tableWeeklyReport);
        if (tableWeeklyReport.getColumnModel().getColumnCount() > 0) {
            tableWeeklyReport.getColumnModel().getColumn(0).setResizable(false);
            tableWeeklyReport.getColumnModel().getColumn(1).setResizable(false);
            tableWeeklyReport.getColumnModel().getColumn(2).setResizable(false);
        }

        panelWeeklyReport.add(scrollPaneWeeklyReport);

        panelTotalAmountWeekly.setLayout(new java.awt.GridLayout(1, 0));

        labelTotalWeeklyNonEditable.setText("Total:");
        panelTotalAmountWeekly.add(labelTotalWeeklyNonEditable);

        labelTotalWeeklyEditable.setText("0.0");
        panelTotalAmountWeekly.add(labelTotalWeeklyEditable);

        panelWeeklyReport.add(panelTotalAmountWeekly);

        add(panelWeeklyReport);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDailyReport;
    private javax.swing.JLabel labelTotalDailyEditable;
    private javax.swing.JLabel labelTotalDailyNonEditable;
    private javax.swing.JLabel labelTotalWeeklyEditable;
    private javax.swing.JLabel labelTotalWeeklyNonEditable;
    private javax.swing.JLabel labelWeeklyReport;
    private javax.swing.JPanel panelDailyReport;
    private javax.swing.JPanel panelTotalAmountDaily;
    private javax.swing.JPanel panelTotalAmountWeekly;
    private javax.swing.JPanel panelWeeklyReport;
    private javax.swing.JScrollPane scrollPaneDailyReport;
    private javax.swing.JScrollPane scrollPaneWeeklyReport;
    private javax.swing.JTable tableDailyReport;
    private javax.swing.JTable tableWeeklyReport;
    // End of variables declaration//GEN-END:variables
}
