/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
 

/**
 *
 * @author Daniel
 */
public class PanelHome extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    
    
    public PanelHome() { 
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        scrollPaneStock = new javax.swing.JScrollPane();
        tableStock = new javax.swing.JTable();
        panelCenter = new javax.swing.JPanel();
        panelTitleSales = new javax.swing.JPanel();
        labelSale = new javax.swing.JLabel();
        panelAddProducts = new javax.swing.JPanel();
        labelQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddSelectedProduct = new javax.swing.JButton();
        panelTitleClient = new javax.swing.JPanel();
        labelDataClient = new javax.swing.JLabel();
        panelDataClient = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelCc = new javax.swing.JLabel();
        txtCc = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        labelAdress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        panelRight = new javax.swing.JPanel();
        scrollPaneOrder = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        panelTotalLabels = new javax.swing.JPanel();
        labelTotalTitle = new javax.swing.JLabel();
        labelTotalAmount = new javax.swing.JLabel();
        btnRegisterSale = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.GridLayout(1, 0));

        panelLeft.setLayout(new java.awt.GridLayout(1, 0));

        tableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Stock", "Precio de venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneStock.setViewportView(tableStock);
        if (tableStock.getColumnModel().getColumnCount() > 0) {
            tableStock.getColumnModel().getColumn(0).setResizable(false);
            tableStock.getColumnModel().getColumn(1).setResizable(false);
            tableStock.getColumnModel().getColumn(2).setResizable(false);
        }

        panelLeft.add(scrollPaneStock);

        add(panelLeft);

        panelCenter.setLayout(new javax.swing.BoxLayout(panelCenter, javax.swing.BoxLayout.Y_AXIS));

        panelTitleSales.setLayout(new java.awt.GridLayout(1, 0));

        labelSale.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelSale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSale.setText("VENDER");
        panelTitleSales.add(labelSale);

        panelCenter.add(panelTitleSales);

        labelQuantity.setText("Cantidad:");

        btnAddSelectedProduct.setText("Agregar producto seleccionado");

        javax.swing.GroupLayout panelAddProductsLayout = new javax.swing.GroupLayout(panelAddProducts);
        panelAddProducts.setLayout(panelAddProductsLayout);
        panelAddProductsLayout.setHorizontalGroup(
            panelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddProductsLayout.createSequentialGroup()
                        .addComponent(labelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantity))
                    .addComponent(btnAddSelectedProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAddProductsLayout.setVerticalGroup(
            panelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddSelectedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCenter.add(panelAddProducts);

        panelTitleClient.setLayout(new java.awt.GridLayout(1, 0));

        labelDataClient.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelDataClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataClient.setText("Datos del cliente:");
        panelTitleClient.add(labelDataClient);

        panelCenter.add(panelTitleClient);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        labelName.setText("Nombre:");

        labelCc.setText("Cedula:");

        txtCc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCcActionPerformed(evt);
            }
        });

        labelPhone.setText("Teléfono:");

        labelAdress.setText("Dirección:");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataClientLayout = new javax.swing.GroupLayout(panelDataClient);
        panelDataClient.setLayout(panelDataClientLayout);
        panelDataClientLayout.setHorizontalGroup(
            panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelAdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(labelPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(txtCc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        panelDataClientLayout.setVerticalGroup(
            panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataClientLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCc)
                    .addComponent(txtCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPhone))
                .addGap(22, 22, 22)
                .addGroup(panelDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdress))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        panelCenter.add(panelDataClient);

        add(panelCenter);

        panelRight.setLayout(new javax.swing.BoxLayout(panelRight, javax.swing.BoxLayout.Y_AXIS));

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneOrder.setViewportView(tableOrder);
        if (tableOrder.getColumnModel().getColumnCount() > 0) {
            tableOrder.getColumnModel().getColumn(0).setResizable(false);
            tableOrder.getColumnModel().getColumn(1).setResizable(false);
            tableOrder.getColumnModel().getColumn(2).setResizable(false);
        }

        panelRight.add(scrollPaneOrder);

        panelTotalLabels.setLayout(new java.awt.GridLayout(1, 0));

        labelTotalTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalTitle.setText("Total:");
        panelTotalLabels.add(labelTotalTitle);

        labelTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalAmount.setText("0.0");
        panelTotalLabels.add(labelTotalAmount);

        panelRight.add(panelTotalLabels);

        btnRegisterSale.setText("Registrar Venta");
        btnRegisterSale.setMaximumSize(new java.awt.Dimension(362, 32));
        btnRegisterSale.setMinimumSize(new java.awt.Dimension(362, 32));
        btnRegisterSale.setPreferredSize(new java.awt.Dimension(362, 32));
        btnRegisterSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSaleActionPerformed(evt);
            }
        });
        panelRight.add(btnRegisterSale);

        add(panelRight);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterSaleActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCcActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSelectedProduct;
    private javax.swing.JButton btnRegisterSale;
    private javax.swing.JLabel labelAdress;
    private javax.swing.JLabel labelCc;
    private javax.swing.JLabel labelDataClient;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelSale;
    private javax.swing.JLabel labelTotalAmount;
    private javax.swing.JLabel labelTotalTitle;
    private javax.swing.JPanel panelAddProducts;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelDataClient;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTitleClient;
    private javax.swing.JPanel panelTitleSales;
    private javax.swing.JPanel panelTotalLabels;
    private javax.swing.JScrollPane scrollPaneOrder;
    private javax.swing.JScrollPane scrollPaneStock;
    private javax.swing.JTable tableOrder;
    private javax.swing.JTable tableStock;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
