/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Daniel
 */
public class PanelCredits extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public PanelCredits() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneCredits = new javax.swing.JScrollPane();
        tableCredits = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnAddCredit = new javax.swing.JButton();
        btnModifyCredit = new javax.swing.JButton();
        btnDeleteCredit = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.BorderLayout());

        tableCredits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Teléfono", "Deuda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneCredits.setViewportView(tableCredits);
        if (tableCredits.getColumnModel().getColumnCount() > 0) {
            tableCredits.getColumnModel().getColumn(0).setResizable(false);
            tableCredits.getColumnModel().getColumn(1).setResizable(false);
            tableCredits.getColumnModel().getColumn(2).setResizable(false);
            tableCredits.getColumnModel().getColumn(3).setResizable(false);
        }

        add(scrollPaneCredits, java.awt.BorderLayout.CENTER);

        panelButtons.setLayout(new java.awt.GridLayout(0, 1));

        btnAddCredit.setText("Agregar Credito");
        btnAddCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCreditActionPerformed(evt);
            }
        });
        panelButtons.add(btnAddCredit);

        btnModifyCredit.setText("Modificar Credito");
        btnModifyCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCreditActionPerformed(evt);
            }
        });
        panelButtons.add(btnModifyCredit);

        btnDeleteCredit.setText("Eliminar Credito");
        btnDeleteCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCreditActionPerformed(evt);
            }
        });
        panelButtons.add(btnDeleteCredit);

        add(panelButtons, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCreditActionPerformed
        // TODO add your handling code here:
        new ModifyCredit();
    }//GEN-LAST:event_btnModifyCreditActionPerformed

    private void btnDeleteCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCreditActionPerformed

    private void btnAddCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCreditActionPerformed
        // TODO add your handling code here:
        
        new AddCredit();
    }//GEN-LAST:event_btnAddCreditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCredit;
    private javax.swing.JButton btnDeleteCredit;
    private javax.swing.JButton btnModifyCredit;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JScrollPane scrollPaneCredits;
    private javax.swing.JTable tableCredits;
    // End of variables declaration//GEN-END:variables
}
